services:
  database:
    image: mysql:8.0.35
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "public_voices"
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - dev

  www:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: website
    ports:
      - "8000:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d 
    environment:
      DATABASE_HOST: database
      DATABASE_USER: root
      DATABASE_PASSWORD: ""
    depends_on:
      - database
    networks:
      - dev

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1026:1025"
      - "8026:8025"
    networks:
      - dev

networks:
  dev:

volumes:
  database_data: